version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  foo:
    image: nginx
    environment:
      - VIRTUAL_HOST=foo.test,bar.test
    ports:
      - "80"
    volumes:
      - ./foo:/usr/share/nginx/html

  baz:
    image: nginx
    environment:
      - VIRTUAL_HOST=baz.test
    ports:
      - "80"
    volumes:
      - ./baz:/usr/share/nginx/html
